# Generated by Django 6.0 on 2026-01-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserConfirmaton',
            new_name='UserConfirmation',
        ),
    ]
